4 mint autófelvevő azt akarom hogy fel tudjak venni egy egyedi autótípust a rendszerbe azért hogy azt az ügyfelek elérhessék milyen típusú kocsikból lehet választani
KTRNinjas/Car-Rental pull request #43
Opened 2022-07-30 15:29 UTC by NeilTomson

@nikik6 @rajnaig1  először lépj be a filldb-be nézd meg hogy a táblázatot legeneráljae sikeresen. Aztán lépj be a view-ba és néz meg (AutoFelvetel.php)hogy feltudsz e venni autotipusokat ;s megjelenek e az adatbázisban. Ha bárhol hiba üzenetet kapsz akkor ne aprovold csinálj egy sqreenshotot légyszives.

2022-07-31 01:14 UTC, rajnaig1 commented on SRC/Controller/AutoFelvevoController.php
> +  print $fajta.$marka;
Ezt tüntesd el, mert randa, ahogy kiprinteli

2022-07-31 01:16 UTC, rajnaig1 commented on SRC/Model/Service/AutoTipusService.php
> +    //Ide kéne egy if($premium==true){$premium=1;}else{$premium=0;} átírás, különben nem működik nálam rajnaig
Ahogy a commentben leírtam, úgy kéne megváltoztatni, hogy mukodjék nálam

2022-07-31 01:22 UTC, rajnaig1 requested changes
![kép](https://user-images.githubusercontent.com/109238551/182005562-40e5eb5c-275c-4fa2-8098-2dff62b7d53e.png)
**Problémáim:**

- Megjelenik kiprintelve Az autó neve, és a fajta id a beküldés gomb előtt, mert maradt egy print kód a Controller 40. sora környékén, aminek nem kéne ott lennie
- Nem tárolja le a kocsit a db-ben, mert sajnos az én rendszerem a $premium=false-ot nem 0-1-ként tárolja le A Service-ben kéne írni egy egyszerű if szerkezetet, ami átalakítja. Beszúrtam egy commentet rá, hogy hová

2022-07-31 23:59 UTC, rajnaig1 approved these changes
Kijavítva, szép munka volt

2022-08-03 08:38 UTC, nikik6 approved these changes
Minden rendben működik.

2022-08-03 09:49 UTC, merged