8 mint user azt akarom hogy tudjak regisztrálni azért hogy később kocsit rendelhessek
KTRNinjas/Car-Rental pull request #46
Opened 2022-08-01 16:31 UTC by nikik6

2022-08-01 16:44 UTC, nikik6 commented
- [ ] checkout to 8-as ág
- [ ] pull-old
- [ ] indítsd el az intall_routing-ot
- [ ] menj a localhost-ra
- [ ] regisztráció linkre kattints
- [ ] töltsd ki az alábbi formot:
![image](https://user-images.githubusercontent.com/109237893/182200329-43224fc4-ad49-4aba-b17d-255967ef7fbd.png)

- [ ] próbáld ki, hogy félig kitöltve hibát dob e
- [ ] ha minden rendben, "Sikeres regisztráció" szöveget ad ki.
Ha hibaüzenetet kapsz légyszi csinálj róla screenshot-ot.

2022-08-02 02:29 UTC, rajnaig1 commented on SRC/Filldb.php
> +function AdatfelvetelAutoFajta($kapcsolat){
Ezt ki lehet szedni az egész Adatefelvételautófajta functiont. Már Attilánál sincs meg, nyugodtan töröld ki,

2022-08-02 02:30 UTC, rajnaig1 commented on SRC/Filldb.php
> +function AdatfelvetelAutoKategoria($kapcsolat){
Ezt ki lehet szedni, az egész adatfelvételautókategória functiont, már Attilánál is kiszedtük

2022-08-02 02:31 UTC, rajnaig1 commented on SRC/Filldb.php
> +function KornyezetvedelmiBesorolas($kapcsolat){
Ezt ki lehet szedni, az egész Kornyezetvedelmi Besorolást, már Attilánál is kiszedtük.

2022-08-02 02:32 UTC, rajnaig1 commented on SRC/Model/DAO/Dbconn.php
> +<?php
Ez a file a Connection mappában már bennevan, úh innét ki kell szedni. Töröld innét a dbconn,php-t, hogy Csak a connection mappában legyen meg

2022-08-02 02:35 UTC, rajnaig1 commented on SRC/Model/DAO/user_dao.php
> +  $ok=mysqli_query($kapcsolat, $sql);
Valamiért nékem nem hajlandó a phpmyadmin letárolni úgy recordot, hogy a role_id és a telefonszám mező üres, úh ha ez a helyzet, akkor le kell tárolnunk egy 0-t, de nem itt, hanem a user_revice.php-ben;

2022-08-02 03:29 UTC, rajnaig1 commented on SRC/registration_data.php
> +    Query($kapcsolat, "contact tábla létrehozása", $sql);
Itt kéne megoldanunk, hogy a telefonszám mező ne legyen kötelezően lenyomandó az adatbázisba. Írd át a $sql-t a következőre:
$sql="CREATE TABLE `autokolcsonzo`.`contact` (`id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT , `Vezetéknév` VARCHAR(50) NOT NULL , `Keresztnév` VARCHAR(50) NOT NULL , `e-mail` VARCHAR(50) NOT NULL , `Password` VARCHAR(50) NOT NULL , `Jogosítvány száma` VARCHAR(20) NOT NULL , `Telefonszám` INT(15) UNSIGNED NULL, `Role_id` INT(10) UNSIGNED NOT NULL , PRIMARY KEY (`id`)) ENGINE = InnoDB";

2022-08-02 03:45 UTC, rajnaig1 requested changes
Nálam sajnos nem sikerált usert letárolni
![kép](https://user-images.githubusercontent.com/109238551/182286422-e76f2644-46e7-40b6-8754-4ba82173fae0.png)

Problémáim:

- [ ] A Filldb-ben bennevan még egy rakás kód, amik Attila autótípusfelvevőjét hajtják. Odacommenteltem mindegyik mellé, hogy mi az, amit ki lehet szedni
- [ ] Ha ezután bármelyik függvényhívás bepirosodik, azt egyelőre commenteld ki, majd Attila kódjából jönni fognak
- [ ] Benne van még a Model/DAO-ban a Dbconn nevezetű file. Ezt ki lehet törölni, mert már a Connection/Dbconnt használja a user_dao.php
- [ ] A user_dao.php-ben meg kell változtatni az egyik sql query-t, hogy adjon NULL értéket a telefonszámnak és 0 értéket egyelőre a role_id-nek, úgy és ott, ahogy azt a commentben írtam
- [ ] A registration_data.php-ben a create_contactban levő $sql-t meg kéne változtatni, úgy, ahogy az a commentben van
Ha mindezekkel végeztél futtasd le a programot, hogy minden működik e nálad, és ha igen requestelj egy új review-t tőlem. A reviewers rajnaig1 mellett két köralakú nyíl.

2022-08-03 02:35 UTC, rajnaig1 approved these changes
Ok, köszönöm, már működik nálam, szép munka volt!

2022-08-03 04:44 UTC, NeilTomson commented
nekem minden rendebn volt

2022-08-03 04:45 UTC, NeilTomson commented
Nekem minden rendben volt

2022-08-03 04:46 UTC, NeilTomson approved these changes
nekem minden rendben volt

2022-08-03 07:21 UTC, merged