19 mint autófelelős képeket akarok feltölteni a kocsikról minden egyes autóról
KTRNinjas/Car-Rental pull request #74
Opened 2022-08-25 16:08 UTC by rajnaig1

- [ ] checkoutolj a 19. ágra
- [ ] futtasd meg a filldb-t
- [ ] futtasd meg a teszteket
- [ ] futtasd meg a filldb-t
- [ ] installáld a routingot(installrouting)
- [ ] menj a localhostra és onnét az autófelvevő honlapjára
- [ ] Ezt kell, hogy lásd:
![kép](https://user-images.githubusercontent.com/109238551/186710167-c3a7f205-2bc0-4f79-8b8d-94a9fad5e301.png)
- [ ] csinálj egy új autót az új autó felvétele gombbal, AMI ELŐTT NINCS + JEL. Miután megjelent nyomj rá a kép feltöltés gombra
- [ ] Próbálj meg feltölteni egy file-t, ami nem jpg/png/jpeg állítsd át hozzá a letöltési ablakban, hogy minden file-t mutasson
- [ ] Ezt kell, hogy lásd:
![kép](https://user-images.githubusercontent.com/109238551/186711650-b6915e16-92e8-4ea6-a4ae-67fb39b50e4e.png)
- [ ] Menj a localhostra, majd menj vissza az oldalra
- [ ] Próbálj meg feltölteni egy jpg/jpeg/png file-t(de ne azt, amelyik már ottvan)
- [ ] A feltöltött képednek meg kell jelennie az első sorban amellett a kocsi mellett, amelyik mellett a képfeltöltés gombot nyomtad
- [ ] menj a localhostra
- [ ] menj vissza az autofelvetel honalpra
- [ ] A képednek még mindig ott kell lennie
- [ ] próbáld meg újra felölteni ugyanazt a képet
- [ ] Ezt kell, hogy lásd:
![kép](https://user-images.githubusercontent.com/109238551/186713539-13f11f4a-1d92-4e8e-93a0-e8caca7df985.png)
- [ ] Menj be az SRC/Fileok/Kepek/Autok mappába. A képednek ott kell lennie
- [ ] Menj be a phpmyadminba, és nézd meg a car images táblát. A képed nevének a path oszlopban kell lennie
- [ ] menj ki a localhostra
- [ ] menj vissza az autofelvetl honlapra
- [ ] Töröld ki az autót
- [ ] A képnek és az autónak el kell tűnnie
- [ ] Menj be az SRC/Fileok/Kepek/Autok mappába. A képednek nem szabad ott lennie
- [ ] Menj be a phpmyadminba, és nézd meg a car images táblát. A képed nevének a path oszlopban nem szabad ottlennie
**Ha bárhol nem azt láttad, ami itt le van írva, vagy hibaüzenetet kaptál, screensholotj, és ne approve-old a pull requestet**

2022-08-26 08:16 UTC, NeilTomson commented
nekem egyik teszt nem futott le először az acceptanciát teszteltem le
![image](https://user-images.githubusercontent.com/100309459/186851889-eeb333cf-3247-41b3-adf3-a208f2c3de77.png)

nem láttom a képet 
![image](https://user-images.githubusercontent.com/100309459/186855900-d7ec5bb0-5377-4677-9814-2b182346914c.png)

2022-08-26 10:03 UTC, nikik6 requested changes
Nekem ugyanazt dobja a teszteknél, mint Atinak:
![image](https://user-images.githubusercontent.com/109237893/186879818-28632dda-a5f1-44c7-8667-c1dc15f114c8.png)
Routingolva nem tudok a localhost/SRC/Fileok/Kepek/Autok mappába menni (miután leszedtem és bementem a mappába megtaláltam a feltöltött képem):
![image](https://user-images.githubusercontent.com/109237893/186880103-53f25653-7b93-43e4-997c-827c75e0149c.png)

A képfeltöltésnél nem jelenik meg a kép, viszont adatbázisban ott van:
![image](https://user-images.githubusercontent.com/109237893/186879740-c7d0458e-387b-4da5-9fb6-7b5131c819c0.png)

2022-08-26 21:56 UTC, nikik6 approved these changes
Teszteken kívül minden működik.
Annyi észrevétel, hogy SRC/Fileok/Kepek/Autok mappába még mindig routing uninstallálásával tudok eljutni.

2022-08-27 08:17 UTC, NeilTomson approved these changes

2022-08-27 21:31 UTC, merged